import { Inter, Quicksand } from "next/font/google";
import "./globals.css";

const quickSand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ami&M",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <body className={`${quickSand.variable} ${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
